# Generated by Django 4.2.5 on 2023-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryAnalyzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("query_count", models.PositiveIntegerField()),
                ("db_time", models.FloatField()),
                ("total_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query_list", models.JSONField()),
            ],
        ),
    ]
